# num = int(input('Digite numeros:'))
# num1 = int(input('Digite numeros:'))
# num2 = int(input('Digite numeros:'))
# num3 = int(input('Digite numeros:'))
# num4 = int(input('Digite numeros:'))
# tupla_numeros = (num, num1, num2, num3, num4)

# maior = max(tupla_numeros)
# menor = min(tupla_numeros)
# soma = sum(tupla_numeros)
# numeros_ordenados = sorted(tupla_numeros)
# print(f'o maior numero é {maior}, o menor numero é {menor} e a soma é {soma}, e a ordem dos numeros é {numeros_ordenados}')